site_name: Kurs Microsoft SQL Server

theme:
  name: material
  language: pl

nav:
  - Strona główna: index.md
  - Autorzy: authors.md
  - Teoria: theory.md
  - Microsoft SQL Server: mssql.md
  - SELECT: select.md
  - INSERT, UPDATE, DELETE: insert-update-delete.md
  - JOIN: joins.md
  - Funkcje SQL: functions.md
  - Ćwiczenia: exercises.md
  - Podsumowanie: summary.md
