site_name: Kurs Microsoft SQL Server

theme:
  name: material
  palette:
    - scheme: default
      primary: purple
      toggle:
        icon: material/weather-night
        name: Dark mode

    - scheme: slate
      primary: purple
      toggle:
        icon: material/weather-sunny
        name: Light mode
nav:
  - Strona główna: index.md
  - Autorzy: authors.md
  - Wstęp: theory.md
  - Microsoft SQL Server: mssql.md
  - SELECT: select.md
  - INSERT UPDATE DELETE: instertupdatedelete.md
  - JOIN: joins.md
  - Funkcje SQL: functions.md
  - Ćwiczenia: exercises.md
  - Podsumowanie: summary.md
